spring.application.name=agenciapublicidad
server.port=8090

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3307/agenciapublicidad
spring.datasource.username=alumno
spring.datasource.password=alumno_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
